name: Blogs@MaskdMafia
url: https://bitcriminals.github.io/
description: Student and CyberSecurity Enthusiast 

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
